# Site settings
title: LeadPages UX
email: brian.reed@ave81.com
description: > # this means to ignore newlines until "baseurl:"
  Built with Jekyll n Stuff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jimfrankenstein

# Build settings
markdown: kramdown
highlighter: true
permalink: /posts/:title

exclude:
  - divshot.json
  - lp-ux.sublime-project
  - lp-ux.sublime-workspace
